// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ChallengeContext))]
    partial class ChallengeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Infrastructure.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionEmployeesId")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WorkAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionEmployeesId");

                    b.HasIndex("PermissionTypeId");

                    b.HasIndex("WorkAreaId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Infrastructure.Models.PermissionsEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PermissionsEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionsEmployeeId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Infrastructure.Models.PermissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionsTypes");
                });

            modelBuilder.Entity("Infrastructure.Models.WorkArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkAreas");
                });

            modelBuilder.Entity("PermissionTypePermissionsEmployee", b =>
                {
                    b.Property<int>("PermissionTypesId")
                        .HasColumnType("int");

                    b.Property<int>("PermisssionsEmployeesId")
                        .HasColumnType("int");

                    b.HasKey("PermissionTypesId", "PermisssionsEmployeesId");

                    b.HasIndex("PermisssionsEmployeesId");

                    b.ToTable("PermissionTypePermissionsEmployee");
                });

            modelBuilder.Entity("Infrastructure.Models.Employee", b =>
                {
                    b.HasOne("Infrastructure.Models.PermissionsEmployee", "PermissionEmployees")
                        .WithMany()
                        .HasForeignKey("PermissionEmployeesId");

                    b.HasOne("Infrastructure.Models.PermissionType", null)
                        .WithMany("Employees")
                        .HasForeignKey("PermissionTypeId");

                    b.HasOne("Infrastructure.Models.WorkArea", "WorkArea")
                        .WithOne("Employee")
                        .HasForeignKey("Infrastructure.Models.Employee", "WorkAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionEmployees");

                    b.Navigation("WorkArea");
                });

            modelBuilder.Entity("Infrastructure.Models.PermissionsEmployee", b =>
                {
                    b.HasOne("Infrastructure.Models.PermissionsEmployee", null)
                        .WithMany("Employees")
                        .HasForeignKey("PermissionsEmployeeId");
                });

            modelBuilder.Entity("PermissionTypePermissionsEmployee", b =>
                {
                    b.HasOne("Infrastructure.Models.PermissionType", null)
                        .WithMany()
                        .HasForeignKey("PermissionTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.PermissionsEmployee", null)
                        .WithMany()
                        .HasForeignKey("PermisssionsEmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Models.PermissionsEmployee", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Infrastructure.Models.PermissionType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Infrastructure.Models.WorkArea", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
